apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-dotnet-prod


patchesJson6902:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: simple-dotnet-service
    version: v1
resources:
- ../../base/
images:
- name: quay.io/froberge/ocp-githubaction-demo
  newTag:0d06b1196a95
