apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: cluster-kubernetes.default.svc-3396314289
  namespace: simple-dotNet-gitops
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: aW4tY2x1c3Rlcg==
  namespaces: c2ltcGxlLXF1YXJrdXMtZGV2LHNpbXBsZS1xdWFya3VzLWdpdG9wcyxzaW1wbGUtcXVhcmt1cy1waXBlbGluZSxzaW1wbGUtcXVhcmt1cy1wcm9k
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
type: Opaque
