apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../argocd-components/argocd-dev-instance
  - tekton
  

resources:
  - namespaces/simple-dotNet-dev.yaml
  - namespaces/simple-dotNet-prod.yaml
  - namespaces/rbac-developer.yaml