apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../argocd-components/argocd-dev-instance

resources:
  - namespaces/simple-dotnet-dev.yaml
  - namespaces/simple-dotnet-prod.yaml
  - namespaces/rbac-developer.yaml