apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-dotnet-dev

resources:
- ../../base/

patchesJson6902:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: simple-dotnet-service
    version: v1
images:
- name: quay.io/froberge/ocp-githubaction-demo
  newTag: bab7c3f245aa
